/**
 * Generates frontend/js/firebase/env.js from root .env file.
 * Run automatically before dev/start/build.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadEnv } from "./env-loader.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const targetDir = path.join(rootDir, "frontend", "js", "firebase");
const targetFile = path.join(targetDir, "env.js");

const env = loadEnv();

const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY OR COMMIT TO VERSION CONTROL.
 * Generated by scripts/generate-env.mjs from .env variables.
 */

export const ENV = {
  FIREBASE_API_KEY: ${JSON.stringify(env.FIREBASE_API_KEY || "")},
  FIREBASE_AUTH_DOMAIN: ${JSON.stringify(env.FIREBASE_AUTH_DOMAIN || "")},
  FIREBASE_PROJECT_ID: ${JSON.stringify(env.FIREBASE_PROJECT_ID || "")},
  FIREBASE_STORAGE_BUCKET: ${JSON.stringify(env.FIREBASE_STORAGE_BUCKET || "")},
  FIREBASE_MESSAGING_SENDER_ID: ${JSON.stringify(env.FIREBASE_MESSAGING_SENDER_ID || "")},
  FIREBASE_APP_ID: ${JSON.stringify(env.FIREBASE_APP_ID || "")},
  FIREBASE_MEASUREMENT_ID: ${JSON.stringify(env.FIREBASE_MEASUREMENT_ID || "")},
  AUTH_USER_KEY: ${JSON.stringify(env.AUTH_USER_KEY || "almar_current_user")},
  AUTH_TOKEN_KEY: ${JSON.stringify(env.AUTH_TOKEN_KEY || "token")},
  AUTH_NAME_KEY: ${JSON.stringify(env.AUTH_NAME_KEY || "adminNombre")},
  STORAGE_KEY_PREFIX: ${JSON.stringify(env.STORAGE_KEY_PREFIX || "almar_")}
};

export default ENV;
`;

if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(targetFile, content, "utf8");
console.log(`[generate-env] Successfully generated frontend/js/firebase/env.js`);
